<?php

namespace AppBundle\Repository;

/**
 * ChecklistCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChecklistCategoryRepository extends \Doctrine\ORM\EntityRepository
{
}
