<?php

namespace AppBundle\Repository;

/**
 * CheckInstanceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CheckInstanceRepository extends \Doctrine\ORM\EntityRepository
{
}
