<?php

namespace AppBundle\Repository;

/**
 * CheckInstanceCheckRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CheckInstanceCheckRepository extends \Doctrine\ORM\EntityRepository
{
}
