<?php

namespace AppBundle\Repository;

/**
 * TaskCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TaskCategoryRepository extends \Doctrine\ORM\EntityRepository
{
}
